package com.github.kennethnickles.gatherer.card;

import android.support.annotation.NonNull;
import android.support.annotation.Nullable;

import android.util.Log;
import com.github.kennethnickles.gatherer.util.Strings;
import com.github.kennethnickles.gatherer.util.Enums;
import com.github.kennethnickles.gatherer.util.Lists;

import java.util.List;

/**
 * @author kenneth.nickles
 * @since 2016-04-04.
 */
public enum Subtype {
    ADVISOR,
    AJANI,
    ALARA,
    ALLY,
    ANGEL,
    ANTELOPE,
    APE,
    ARCANE,
    ARCHER,
    ARCHON,
    ARKHOS,
    ARLINN,
    ARTIFICER,
    ASHIOK,
    ASSASSIN,
    ASSEMBLY_WORKER("ASSEMBLY-WORKER"),
    ATOG,
    AURA,
    AUROCHS,
    AVATAR,
    AZGOL,
    BADGER,
    BARBARIAN,
    BASILISK,
    BAT,
    BEAR,
    BEAST,
    BEEBLE,
    BELENON,
    BERSERKER,
    BIRD,
    BOAR,
    BOLAS,
    BOLASS_MEDITATION_REALM("BOLAS’S MEDITATION REALM"),
    BRINGER,
    BRUSHWAGG,
    CAMEL,
    CARRIER,
    CAT,
    CENTAUR,
    CEPHALID,
    CHANDRA,
    CHICKEN,
    CHIMERA,
    CLERIC,
    COCKATRICE,
    CONSTRUCT,
    CRAB,
    CROCODILE,
    CURSE,
    CYCLOPS,
    DACK,
    DARETTI,
    DAUTHI,
    DEMON,
    DESERT,
    DEVIL,
    DJINN,
    DOMINARIA,
    DOMRI,
    DRAGON,
    DRAKE,
    DREADNOUGHT,
    DRONE,
    DRUID,
    DRYAD,
    DWARF,
    EFREET,
    ELDER,
    ELDRAZI,
    ELEMENTAL,
    ELEPHANT,
    ELF,
    ELK,
    ELSPETH,
    EQUILOR,
    EQUIPMENT,
    ERGAMON,
    EYE,
    FABACIN,
    FAERIE,
    FERRET,
    FISH,
    FLAGBEARER,
    FOREST,
    FORTIFICATION,
    FOX,
    FREYALISE,
    FROG,
    FUNGUS,
    GARGOYLE,
    GARRUK,
    GATE,
    GIANT,
    GIDEON,
    GNOME,
    GOAT,
    GOBLIN,
    GOD,
    GOLEM,
    GORGON,
    GREMLIN,
    GRIFFIN,
    HAG,
    HARPY,
    HELLION,
    HIPPO,
    HIPPOGRIFF,
    HOMARID,
    HOMUNCULUS,
    HORROR,
    HORSE,
    HOUND,
    HUMAN,
    HYDRA,
    HYENA,
    ILLUSION,
    IMP,
    INCARNATION,
    INNISTRAD,
    INSECT,
    IQUATANA,
    IR,
    ISLAND,
    JACE,
    JELLYFISH,
    JUGGERNAUT,
    KALDHEIM,
    KAMIGAWA,
    KARN,
    KAVU,
    KEPHALAI,
    KIORA,
    KIRIN,
    KITHKIN,
    KNIGHT,
    KOBOLD,
    KOLBAHAN,
    KOR,
    KOTH,
    KRAKEN,
    KYNETH,
    LAIR,
    LAMIA,
    LAMMASU,
    LEECH,
    LEGEND,
    LEVIATHAN,
    LHURGOYF,
    LICID,
    LILIANA,
    LIZARD,
    LOCUS,
    LORWYN,
    MANTICORE,
    MASTICORE,
    MERCADIA,
    MERCENARY,
    MERFOLK,
    METATHRAN,
    MINE,
    MINION,
    MINOTAUR,
    MIRRODIN,
    MOAG,
    MOLE,
    MONGER,
    MONGOOSE,
    MONGSENG,
    MONK,
    MOONFOLK,
    MOUNTAIN,
    MURAGANDA,
    MUTANT,
    MYR,
    MYSTIC,
    NAGA,
    NAHIRI,
    NARSET,
    NAUTILUS,
    NEPHILIM,
    NEW_PHYREXIA("NEW PHYREXIA"),
    NIGHTMARE,
    NIGHTSTALKER,
    NINJA,
    NISSA,
    NIXILIS,
    NOGGLE,
    NOMAD,
    NYMPH,
    OCTOPUS,
    OGRE,
    OOZE,
    ORC,
    ORGG,
    OUPHE,
    OX,
    OYSTER,
    PEGASUS,
    PEST,
    PHELDDAGRIF,
    PHOENIX,
    PHYREXIA,
    PIRATE,
    PLAINS,
    PLANT,
    POWER_PLANT,
    PRAETOR,
    PROCESSOR,
    RABBIT,
    RABIAH,
    RAL,
    RAT,
    RATH,
    RAVNICA,
    REBEL,
    REGATHA,
    RHINO,
    RIGGER,
    ROGUE,
    SABLE,
    SALAMANDER,
    SAMURAI,
    SAPROLING,
    SARKHAN,
    SATYR,
    SCARECROW,
    SCORPION,
    SCOUT,
    SEGOVIA,
    SERPENT,
    SERRAS_REALM("SERRA’S REALM"),
    SHADE,
    SHADOWMOOR,
    SHAMAN,
    SHANDALAR,
    SHAPESHIFTER,
    SHEEP,
    SHRINE,
    SIREN,
    SKELETON,
    SLITH,
    SLIVER,
    SLUG,
    SNAKE,
    SOLDIER,
    SOLTARI,
    SORIN,
    SPAWN,
    SPECTER,
    SPELLSHAPER,
    SPHINX,
    SPIDER,
    SPIKE,
    SPIRIT,
    SPONGE,
    SQUID,
    SQUIRREL,
    STARFISH,
    SURRAKAR,
    SWAMP,
    TAMIYO,
    TEFERI,
    TEZZERET,
    THALAKOS,
    THOPTER,
    THRULL,
    TIBALT,
    TOWER,
    TRAP,
    TREEFOLK,
    TROLL,
    TURTLE,
    UGIN,
    ULGROTHA,
    UNICORN,
    URZAS("URZA’S"),
    VALLA,
    VAMPIRE,
    VEDALKEN,
    VENSER,
    VIASHINO,
    VOLVER,
    VRASKA,
    VRYN,
    WALL,
    WARRIOR,
    WEIRD,
    WEREWOLF,
    WHALE,
    WILDFIRE,
    WIZARD,
    WOLF,
    WOLVERINE,
    WOMBAT,
    WORM,
    WRAITH,
    WURM,
    XENAGOS,
    XEREX,
    YETI,
    ZENDIKAR,
    ZOMBIE,
    ZUBERA;

    private final String mName;

    Subtype() {
        this.mName = name();
    }

    Subtype(String name) {
        this.mName = name;
    }

    @NonNull
    public String getName() {
        return mName;
    }

    @Nullable
    public static Subtype from(String lookup) {
        if (Strings.isNullOrEmpty(lookup)) {
            return null;
        }
        for (Subtype subtype : values()) {
            if (subtype.getName().equals(Enums.sanitize(lookup))) {
                return subtype;
            }
        }
        Log.d("Subtype", "Missing Subtype: " + lookup);
        return null;
    }

    @Nullable
    public static List<Subtype> from(List<String> lookups) {
        if (lookups == null || lookups.isEmpty()) {
            return Lists.newArrayList();
        }
        final List<Subtype> types = Lists.newArrayList();
        for (String lookup : lookups) {
            types.add(from(lookup));
        }
        return types;
    }
}
